/// Poster Request data models
library;

import 'package:hive/hive.dart';

part 'poster_request.g.dart';

/// Represents a poster pull request sent from Front Desk to Back Office
///
/// This is the core data structure for the Poster Runner application.
/// All state changes are persisted locally using Hive and transmitted
/// via BLE between Front Desk and Back Office devices.
///
/// **Field Naming Note:**
/// Field names align with the Data Structure Specification (uniqueId, timestampPulled)
/// rather than Dart conventions to maintain consistency with BLE protocol and
/// cross-platform data interchange.
@HiveType(typeId: 0)
class PosterRequest {
  /// Unique identifier for this request (UUID)
  ///
  /// Generated by Front Desk upon submission. Used as the Hive box key
  /// for fast retrieval and updates.
  @HiveField(0)
  final String uniqueId;

  /// Alphanumeric poster number requested by the client
  ///
  /// Examples: "A457", "B211", "C003"
  /// Used for sorting in the Delivered Audit screen (alphanumeric ascending)
  @HiveField(1)
  final String posterNumber;

  /// Timestamp when the request was submitted by Front Desk
  ///
  /// Used for Queue sorting (chronological, oldest first)
  /// Stored in UTC, formatted as ISO 8601 for BLE transmission
  @HiveField(2)
  final DateTime timestampSent;

  /// Timestamp when Back Office marked the request as fulfilled
  ///
  /// Null if request is not yet fulfilled (status: sent or pending)
  /// Set by Back Office when user clicks "PULL" button
  @HiveField(3)
  final DateTime? timestampPulled;

  /// Current lifecycle status of the request
  ///
  /// Controls which screen the request appears on and available actions
  @HiveField(4)
  final RequestStatus status;

  /// Whether current state has been successfully transmitted via BLE
  ///
  /// - Set to `false` when state changes occur offline
  /// - Set to `true` after successful BLE transmission
  /// - Drives re-sync logic when connection is restored
  ///
  /// **Front Desk:**
  /// - `false` after creating new request (before BLE write succeeds)
  /// - `true` after Back Office acknowledges receipt
  ///
  /// **Back Office:**
  /// - `true` when receiving new request from Front Desk
  /// - `false` after marking fulfilled (before indication sent to Front Desk)
  /// - `true` after Front Desk acknowledges status update
  @HiveField(5)
  final bool isSynced;

  /// Creates a new PosterRequest instance
  const PosterRequest({
    required this.uniqueId,
    required this.posterNumber,
    required this.timestampSent,
    this.timestampPulled,
    required this.status,
    this.isSynced = false,
  });

  /// Creates a copy of this request with updated fields
  ///
  /// Used for immutable state updates throughout the application
  PosterRequest copyWith({
    String? uniqueId,
    String? posterNumber,
    DateTime? timestampSent,
    DateTime? timestampPulled,
    RequestStatus? status,
    bool? isSynced,
  }) {
    return PosterRequest(
      uniqueId: uniqueId ?? this.uniqueId,
      posterNumber: posterNumber ?? this.posterNumber,
      timestampSent: timestampSent ?? this.timestampSent,
      timestampPulled: timestampPulled ?? this.timestampPulled,
      status: status ?? this.status,
      isSynced: isSynced ?? this.isSynced,
    );
  }

  /// Serializes this request to JSON for BLE transmission
  ///
  /// DateTime objects are converted to ISO 8601 strings.
  /// The `isSynced` field is excluded as it's local-only.
  Map<String, dynamic> toJson() {
    return {
      'uniqueId': uniqueId,
      'posterNumber': posterNumber,
      'timestampSent': timestampSent.toIso8601String(),
      'timestampPulled': timestampPulled?.toIso8601String(),
      'status': status.name,
      // Note: isSynced is NOT transmitted - it's a local-only field
    };
  }

  /// Creates a PosterRequest from JSON data received via BLE
  ///
  /// Handles DateTime parsing from ISO 8601 strings.
  /// Sets `isSynced` based on receiving context (see [fromJsonSynced]).
  factory PosterRequest.fromJson(Map<String, dynamic> json) {
    return PosterRequest(
      uniqueId: json['uniqueId'] as String,
      posterNumber: json['posterNumber'] as String,
      timestampSent: DateTime.parse(json['timestampSent'] as String),
      timestampPulled: json['timestampPulled'] != null
          ? DateTime.parse(json['timestampPulled'] as String)
          : null,
      status: RequestStatus.values.firstWhere(
        (e) => e.name == json['status'],
        orElse: () => RequestStatus.sent,
      ),
      isSynced: false, // Default to false, use fromJsonSynced for synced data
    );
  }

  /// Creates a PosterRequest from JSON with explicit sync state
  ///
  /// Use this when receiving data via BLE that should be marked as synced.
  ///
  /// **Example:**
  /// ```dart
  /// // Front Desk receiving acknowledgment from Back Office
  /// final request = PosterRequest.fromJsonSynced(bleData, isSynced: true);
  /// ```
  factory PosterRequest.fromJsonSynced(
    Map<String, dynamic> json, {
    required bool isSynced,
  }) {
    return PosterRequest(
      uniqueId: json['uniqueId'] as String,
      posterNumber: json['posterNumber'] as String,
      timestampSent: DateTime.parse(json['timestampSent'] as String),
      timestampPulled: json['timestampPulled'] != null
          ? DateTime.parse(json['timestampPulled'] as String)
          : null,
      status: RequestStatus.values.firstWhere(
        (e) => e.name == json['status'],
        orElse: () => RequestStatus.sent,
      ),
      isSynced: isSynced,
    );
  }

  /// Serializes for Request Characteristic (A) transmission
  ///
  /// Front Desk → Back Office: Sends only initial request fields
  Map<String, dynamic> toRequestCharacteristicJson() {
    return {
      'uniqueId': uniqueId,
      'posterNumber': posterNumber,
      'timestampSent': timestampSent.toIso8601String(),
    };
  }

  /// Serializes for Queue Status Characteristic (B) transmission
  ///
  /// Back Office → Front Desk: Sends status update
  Map<String, dynamic> toQueueStatusJson() {
    return {
      'uniqueId': uniqueId,
      'status': status.name,
      'timestampPulled': timestampPulled?.toIso8601String(),
    };
  }

  /// Check if request is fulfilled
  bool get isFulfilled => status == RequestStatus.fulfilled;

  /// Check if request is pending
  bool get isPending => status == RequestStatus.pending;

  /// Check if request is sent but not acknowledged
  bool get isSent => status == RequestStatus.sent;

  /// Check if request needs to be synced via BLE
  bool get needsSync => !isSynced;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PosterRequest &&
          runtimeType == other.runtimeType &&
          uniqueId == other.uniqueId &&
          posterNumber == other.posterNumber &&
          timestampSent == other.timestampSent &&
          timestampPulled == other.timestampPulled &&
          status == other.status &&
          isSynced == other.isSynced;

  @override
  int get hashCode =>
      uniqueId.hashCode ^
      posterNumber.hashCode ^
      timestampSent.hashCode ^
      timestampPulled.hashCode ^
      status.hashCode ^
      isSynced.hashCode;

  @override
  String toString() {
    return 'PosterRequest('
        'uniqueId: $uniqueId, '
        'posterNumber: $posterNumber, '
        'status: ${status.name}, '
        'timestampSent: $timestampSent, '
        'timestampPulled: $timestampPulled, '
        'isSynced: $isSynced'
        ')';
  }
}

/// Status of a poster request in its lifecycle
///
/// The status controls which screen the request appears on and
/// what actions are available to the user.
@HiveType(typeId: 1)
enum RequestStatus {
  /// Request sent from Front Desk, awaiting acknowledgment
  ///
  /// - Set by: Front Desk (upon creation)
  /// - Appears on: Front Desk Request Entry screen
  /// - Next state: pending (when Back Office acknowledges)
  @HiveField(0)
  sent,

  /// Acknowledged by Back Office, being fulfilled
  ///
  /// - Set by: Back Office (upon receiving request)
  /// - Appears on: Back Office Live Queue screen
  /// - Next state: fulfilled (when user clicks "PULL")
  @HiveField(1)
  pending,

  /// Completed successfully by Back Office
  ///
  /// - Set by: Back Office (when marking as pulled)
  /// - Appears on: Both Delivered Audit and Fulfilled Log screens
  /// - Final state: No further transitions
  @HiveField(2)
  fulfilled,
}

/// Extension methods for RequestStatus enum
extension RequestStatusExtension on RequestStatus {
  /// Display label for status
  ///
  /// Used in UI badges and status indicators
  String get label {
    switch (this) {
      case RequestStatus.sent:
        return 'SENT';
      case RequestStatus.pending:
        return 'PENDING';
      case RequestStatus.fulfilled:
        return 'FULFILLED';
    }
  }

  /// Icon representation for status
  ///
  /// Used in UI for quick visual identification
  String get icon {
    switch (this) {
      case RequestStatus.sent:
        return '→'; // Arrow for sent
      case RequestStatus.pending:
        return '⏳'; // Hourglass for pending
      case RequestStatus.fulfilled:
        return '✓'; // Checkmark for fulfilled
    }
  }

  /// Serializes enum to string for JSON transmission
  String toJson() => name;

  /// Deserializes enum from string
  static RequestStatus fromJson(String json) {
    return RequestStatus.values.firstWhere(
      (e) => e.name == json,
      orElse: () => RequestStatus.sent,
    );
  }
}
